# Generated by Django 5.2 on 2026-06-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('confianza', models.FloatField(default=0.0, help_text='Porcentaje de confianza en la identificación (0-100)')),
                ('cantidad_plantas', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de plantas detectadas')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('imagen_procesada', models.ImageField(blank=True, help_text='Imagen con detecciones dibujadas', upload_to='processed/%Y/%m/%d/')),
                ('datos_json', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales del análisis')),
            ],
            options={
                'verbose_name': 'Análisis de Imagen',
                'verbose_name_plural': 'Análisis de Imágenes',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cultivo',
                'verbose_name_plural': 'Tipos de Cultivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.analisisimagen')),
            ],
            options={
                'verbose_name': 'Registro de Análisis',
                'verbose_name_plural': 'Registros de Análisis',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='analisisimagen',
            name='tipo_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.tipocultivo', verbose_name='Tipo de cultivo identificado'),
        ),
    ]
